### ISSUE TITLE
Progression beyond "Grade A unlocked"

### ISSUE THREAD

**Issue by CaptainSlow72** [abesto/ams2-career#47] opened 2022-05-27 12:38 UTC
Description:
There seems to be a bug, at least at karting series.
When you record a result in grade A (even it is 1st place) the "A" in the path is not replaced by a checkmark symbol.
Maybe also same behaviour for other series, not tested yet.
Grade A for karting series was unlocked without driving any karting series, but gaining enough XP from driving other series.

**Comment by abesto** [comment] 2022-05-27 19:22
Hi, thanks for the report, @CaptainSlow72! Hm, interesting. For what it's worth, this is working as intended: "completing" a grade currently means moving up to the next grade. Since there's no grade after A, you just ... kind of ... stay there, and stop gaining XP.

So on one hand this is confusing as it's inconsistent with the other grades; and on the other, maybe there should be some progression inside grade A towards "you've now totally mastered this discipline". @rsr427 what do you think?

**Comment by CaptainSlow72** [comment] 2022-05-27 21:14
Hi, just replace the "A" by a checkmark symbol after recorded first time, so one can distinguish if this final race of a series has been unlocked (grade "A" is now available to be recorded) or was recorded at least once ("mastered", indicated by the checkmark symbol).
Just keep it simple and consistent.

**Comment by abesto** [comment] 2022-05-27 21:56
To keep things consistent (and to maintain a sense of progression), I'd expect the XP needed to go from "grade A unlocked" to "grade A mastered" to be a natural progression on the XP curve so far. The nudge for @rsr427 is mostly because he designed the progression system so far, and I'd be most comfortable with him sorting good-feeling numbers here as well.

We could also take it a step further btw: some kind of "prestige" levels (as seen in Diablo 3 for example) where each new level after unlocking grade A brings ... more challenges? Not sure what that'd look like, maybe an AI level bump I guess. Or at least an infinite number of prestige levels to unlock with appropriately scaled XP costs.

**Comment by rsr427** [comment] 2022-05-28 03:11
First, kudos to you @CaptainSlow72 for spending time in the karts. I couldn't do it...  I don't think it's unrealistic to be considered a grade A Karter without having ever raced a kart. If I got licenced and qualified for a GT4 race, I'm sorry, but you better consider a grade A Karter.

It is a very good question as to what to do when you reach the top. I'll admit I should have one more level to complete when you reach the top cars. I have to confer with @abesto , but maybe at that point, the game unlocks a suggested season with a certain number of races at a random selection of tracks. The goal is to win the championship at the top of that discipline.  What say you all?

**Comment by CaptainSlow72** [comment] 2022-05-28 05:14
The more to do as a player in the career the better.
As you (rsr) already know from the Reiza forum, I would like to have a much more expanded career with many many many more series or challenges.
But for a starter we just need an indication if a grade was unlocked or mastered. In its current state, you cannot see if just unlocked or already mastered.

By the way, great app, I love it and it keeps me playing AMS 2.

**Comment by abesto** [comment] 2022-06-03 08:50
After giving this a bit of thought, I'd propose approaching this in three phases:
1. @rsr427 figures out XP numbers for each discipline that make sense for going from "Grade A is unlocked" to "Grade A is mastered". I'll plug it into the app, and update the special-case logic for handling Grade A accordingly. This fixes the immediate confusion, and adds gameplay value for Grade A.
2. Let's figure out a closed formula for "how much XP do you need to go from Grade X to Grade X+1 in discipline D". This will probably need to take a hard-coded parameter for how "hard" a discipline is, or maybe something more complex to better describe a specific XP curve. This allows us to remove the hard-coded XP breakpoints, and makes it much cheaper to add / remove disciplines and grades. Once that's done, I'd close this issue as properly fixed.
3. Let's break out a separate [discussion](https://github.com/abesto/ams2-career/discussions) about next steps for enriching gameplay. Maybe that's more challenges, maybe it's end-game only, maybe a completely different format for the complete progression (ideas for a *proper* career mode with teams, championships, and so on have been thrown around).

Note that for 1. and 2. changes will be applied retroactively whenever a new version rolls out _and_ players reload the app - this is as designed. There may potentially be some confusion ("hey, didn't I already unlock X?"), but it feels like the obviously better choice than "you have to completely restart from scratch" (and I don't have the bandwidth to implement user-controlled version switching). We may want to start thinking about a changelog popup.

**Comment by rsr427** [comment] 2022-06-03 18:42
@abesto I should share with you the sketchup for my next idea.  Its a lot more procedural based as far as car class and xp and unlocks.  There are more variables like License Points and Rep Points, but stuff related to cars is different.  There are 15 total grades, with F1 at the top and club at the bottom.  Open wheel C might be on Level 4, whereas Club grade C would be level 13.  The progression is based more on the level and not an XP table that is specific to a car.  

Uses the came car class labels at this time and track matrix.  Cars still need to be stuck into a level, but that's not that tough.  The progression and reward tables are already created.

**Comment by rsr427** [comment] 2022-06-08 20:35
> Hm, 12XP for the Special discipline seems weird. It takes 12.5 to go from Grade B to Grade A, feels like it should take more than that to finish Grade A?

I used the debugger to see how much XP is earned in each discipline and it seems 3 is about the max in Special.  So 5 good races will see you hit that milestone.

https://ibb.co/jGG7cZB

**Closed** 2022-06-08 21:21 UTC
Labels: enhancement

**Comment by abesto** [comment] 2022-06-12 20:14
To make sure stuff here isn't forgotten, I've
* Filed #56 
* Filed #57
* Pasted ideas that seemed relevant into #50
